### ISSUE TITLE
Not enough Logical Drives were detected (Network PXE Boot)

### ISSUE THREAD

**Issue by Harry3co** [cregx/mdt-cleanup-harddrive-winpe#6]
After starting up into WINPE and the GUI appears, it tells that it only detected 2 logical drives. We are staging our devices only with a C: Drive. Any Chance that we i can get it to work? 

Thanks a lot for your work.

Cheers

**Comment by Harry3co** [comment]
Hey @cregx 
Thanks for your quick respond! We are staging with network pxe boot and normal 0 Touch MDT afterwards. Yes our notebooks Dell XPS 9320/9350 have 1 physical hard drive which gets formatted only with a C: Partition, since our devices get enrolled into azure cloud, we don't need 2 partitions anymore. But if we are not booting on an usb media it shouldn't be a problem using the old version if i understand you right?
Regards
Harry

**Comment by cregx** [comment]
Hello @Harry3co,

yes, that's correct. The older version doesn't have this issue and should work within your PXE-based solution. Currently, I don't have a way to reliably verify whether the boot process is initiated via a boot media (USB) or via PXE. It will take some time to implement a fix and release an updated version of Cleanup. Apologies for the inconvenience. Please let me know if version [1.1.6](https://github.com/cregx/mdt-cleanup-harddrive-winpe/releases/tag/v.1.1.6) at least temporarily resolves your issue. Thank you.

Best regards

**Comment by Harry3co** [comment]
Hey man
Thanks a lot for your help, i tested it with v1.1.6 and it works perfectly like this.

Really appreciated tool.

Take Care
